services:
  - type: web
    name: fashionstyle-backend
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HUGGING_FACE_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: VITE_API_URL
        sync: false
      - key: VITE_S3_BUCKET
        sync: false
      - key: VITE_AWS_REGION
        sync: false
      - key: VITE_USER_POOL_ID
        sync: false
      - key: VITE_USER_POOL_CLIENT_ID
        sync: false
      - key: COGNITO_CLIENT_ID
        sync: false
      - key: COGNITO_CLIENT_SECRET
        sync: false
